version: 2.1
jobs:
  build:
    docker:
        - image: circleci/node
        - image: circleci/mongo:3.5.9
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run db:setup
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test